"""Data models for AWS Events API responses.

Generated by hand from the OpenAPI description at
https://api.awsevents.com/v1/openapi.json (v1.0.0, checked in as
``fixtures/openapi.json``). The guide says any session field may be absent, so
every field the spec does not mark required is optional. Enum-like values are
kept as plain strings because new values are added over time.
"""

from __future__ import annotations

import re
from datetime import date, datetime, timedelta
from zoneinfo import ZoneInfo, ZoneInfoNotFoundError

from pydantic import BaseModel, ConfigDict, Field
from pydantic.alias_generators import to_camel


class _Model(BaseModel):
    model_config = ConfigDict(extra="allow", populate_by_name=True, alias_generator=to_camel)


# --- events -----------------------------------------------------------------


class EventAddress(_Model):
    city: str | None = None


class Event(_Model):
    event_id: str
    name: str
    event_type: str
    start_date: datetime
    end_date: datetime
    is_online: bool
    authentication_required: bool
    timezone: str | None = None
    timezone_abbreviation: str | None = None
    time_format: str | None = None
    address: EventAddress | None = None
    supported_language_codes: list[str] = Field(default_factory=list)


# --- sessions ---------------------------------------------------------------

# SeatAvailability bands, present only on reservable sessions.
SEAT_AVAILABLE = "available"
SEAT_LIMITED = "limited"
SEAT_VERY_LIMITED = "veryLimited"
SEAT_UNAVAILABLE = "unavailable"
SEAT_WALK_UP = "walkUp"


class SessionTime(_Model):
    date: str | None = None  # "2025-12-02"
    time: str | None = None  # local start, "16:00"
    length: str | None = None  # minutes, "60"
    timezone: str | None = None


class Speaker(_Model):
    name: str | None = None


class Session(_Model):
    session_id: str
    title: str
    abbreviation: str | None = None  # public session code, e.g. "AIM3315"
    abstract: str | None = None
    type: str | None = None
    level: str | None = None
    venue: str | None = None
    room: str | None = None
    is_all_day_session: bool = False
    is_reservable: bool = False
    seat_availability: str | None = None
    session_time: SessionTime | None = None
    speakers: list[Speaker] = Field(default_factory=list)
    tracks: list[str] = Field(default_factory=list)
    topics: list[str] = Field(default_factory=list)
    industries: list[str] = Field(default_factory=list)
    areas_of_interest: list[str] = Field(default_factory=list)
    roles: list[str] = Field(default_factory=list)
    services: list[str] = Field(default_factory=list)
    segments: list[str] = Field(default_factory=list)
    features: list[str] = Field(default_factory=list)
    customer_personas: list[str] = Field(default_factory=list)
    experiences: list[str] = Field(default_factory=list)
    additional_activities: list[str] = Field(default_factory=list)
    focus_areas: list[str] = Field(default_factory=list)

    @property
    def code(self) -> str:
        return self.abbreviation or self.session_id

    @property
    def level_number(self) -> int | None:
        """'300 – Advanced' (en dash in the live catalog) or '300 - Advanced' -> 300."""
        m = re.match(r"\s*(\d{3})\b", self.level or "")
        return int(m.group(1)) if m else None

    @property
    def day(self) -> date | None:
        st = self.session_time
        return date.fromisoformat(st.date) if st and st.date else None

    @property
    def start(self) -> datetime | None:
        """Local wall-clock start (naive), in the session's or event's timezone."""
        st = self.session_time
        if not (st and st.date and st.time):
            return None
        return datetime.fromisoformat(f"{st.date}T{st.time}")

    @property
    def duration(self) -> timedelta | None:
        st = self.session_time
        if not (st and st.length and st.length.strip().isdigit()):
            return None
        return timedelta(minutes=int(st.length))

    @property
    def end(self) -> datetime | None:
        return self.start + self.duration if self.start and self.duration else None

    def start_at(self, default_tz: str) -> datetime | None:
        """Timezone-aware start. Uses the session's IANA zone when it has one."""
        if self.start is None:
            return None
        tz_name = (self.session_time.timezone if self.session_time else None) or default_tz
        try:
            tz = ZoneInfo(tz_name)
        except (ZoneInfoNotFoundError, ValueError):
            tz = ZoneInfo(default_tz)
        return self.start.replace(tzinfo=tz)

    @property
    def speaker_names(self) -> list[str]:
        return [s.name for s in self.speakers if s.name]


# --- schedule ---------------------------------------------------------------


class PersonalTime(_Model):
    """A personal time entry. Times are UTC ``YYYY-MM-DDTHH:MM:SS`` with no offset."""

    personal_time_id: str
    title: str
    description: str
    start_date_time: datetime
    end_date_time: datetime
    location: str | None = None


class Schedule(_Model):
    reserved: list[str] = Field(default_factory=list)  # session IDs
    favorites: list[str] = Field(default_factory=list)  # session IDs
    personal_time: list[PersonalTime] = Field(default_factory=list)


# --- bulk writes (ReserveSessions, AssociateFavorites) ----------------------

# BulkFailureCode values. Treat anything else as a refusal we cannot act on.
FAIL_NOT_RESERVABLE = "sessionNotReservable"
FAIL_CONFLICT = "scheduleConflict"
FAIL_ALREADY_SCHEDULED = "alreadyScheduled"
FAIL_FULL = "sessionFull"
FAIL_INSUFFICIENT_ACCESS = "insufficientAccess"
FAIL_TIME_PASSED = "timePassed"
FAIL_ALREADY_FAVORITED = "alreadyFavorited"
FAIL_NOT_FAVORITED = "notFavorited"
FAIL_OTHER = "other"


class BulkFailure(_Model):
    session_id: str
    code: str
    conflicts_with: list[str] = Field(default_factory=list)  # overlapping session IDs

    @property
    def is_full(self) -> bool:
        return self.code == FAIL_FULL

    @property
    def is_conflict(self) -> bool:
        return self.code == FAIL_CONFLICT

    @property
    def already_done(self) -> bool:
        """The desired state already holds, so this failure is harmless."""
        return self.code in (FAIL_ALREADY_SCHEDULED, FAIL_ALREADY_FAVORITED)


class BulkResult(_Model):
    """ReserveSessions and AssociateFavorites return 200 even on partial failure:
    always read ``failed``."""

    successful: list[str] = Field(default_factory=list)
    failed: list[BulkFailure] = Field(default_factory=list)
